<?php
    require_once "beg.php";
?>
    <a href="#" class="scrollup"></a>
    <main>
        <article>
            <div id="content">

                <header>
                    <div class="podnaglowek">Koncerty</div>
                </header>
                
                <section>
                    <div id="concert_div">
                        <div><a href="#zeszle" class="koncertLink" id="link1">Zeszłe koncerty</a></div>
                        <div><a href="#przyszle" class="koncertLink" id="link2">Przyszłe koncerty</a></div>
                        <div><a href="#mapa_trasy" class="koncertLink" id="link3">Trasa koncertowa</a></div>
                    </div>
                </section>

                <hr>

                <img src="img/concert1.jpg" alt="" style="width: 100%; border-radius: 20px; margin-top: 30px;" class="img_cien" id="nag1"/> 

                <section>
                    <div class="podnaglowek" id="zeszle">Zeszłe koncerty</div>
                    <p>Sed id lacinia mauris, quis porttitor risus. Ut semper congue lectus at cursus. In hac habitasse platea dictumst. In blandit laoreet neque, quis blandit lectus porttitor non. Fusce pretium nibh id erat rutrum sagittis. Morbi viverra augue nec justo varius, eget vulputate sem commodo. Aliquam sed gravida arcu, id convallis ipsum. Integer a quam viverra, posuere sapien at, tristique tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque et viverra ligula. Donec ut dui ullamcorper dolor laoreet hendrerit. Maecenas ac tellus laoreet, laoreet enim vitae, tincidunt lorem. Cras elit dolor, luctus congue eleifend vel, semper sed ipsum. Etiam bibendum eleifend ex eu suscipit. Sed quis congue elit. Aenean et neque ac sem pharetra maximus. Sed id ipsum nec enim sodales blandit at eu ante. Maecenas mollis consequat porttitor. Proin et mauris quam.</p>

                    <p>Vivamus venenatis hendrerit risus, non iaculis dui scelerisque et. Nam eget erat odio. Morbi sit amet magna et ipsum aliquet sollicitudin sed id enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque sit amet iaculis lectus. Aliquam vehicula ex sed eleifend auctor. Nunc porttitor dolor ex, eu mollis dui tincidunt ut. Donec dapibus ultrices nulla et rhoncus. Quisque luctus sit amet libero at aliquam. Nunc lobortis, ex a vestibulum porttitor, ex nulla rhoncus quam, a vehicula mauris sapien eu lectus. Proin at neque sed odio aliquam pulvinar. Donec fermentum sapien eu blandit pulvinar. Morbi tristique eros et massa efficitur pretium. Donec vel ornare mauris. Pellentesque ultricies dui ut sapien finibus, et scelerisque nunc lobortis. Cras suscipit, nibh placerat mattis semper, nunc urna finibus nisi, vitae varius quam nisl ac arcu. Aliquam pretium, neque in condimentum maximus, orci diam fermentum dolor, quis tempus odio metus sed magna. Vestibulum ullamcorper, enim pulvinar consectetur semper, orci quam semper nisi, nec consectetur libero erat sed elit. Nunc maximus et nisl nec interdum. Cras nec nisi blandit, vulputate nunc ac, aliquet elit. Maecenas non euismod dolor, at tincidunt ante. Proin vel mauris ut felis dictum efficitur. Curabitur sed magna dui. Phasellus enim mauris, commodo eget enim sit amet, accumsan congue sem. Duis venenatis leo eros, at eleifend lectus dignissim nec. Maecenas non porttitor libero, vitae suscipit lectus. Fusce vitae justo eros.</p>

                    Ut condimentum tellus eget pharetra porta. Nulla eu augue velit. Aenean interdum, elit quis mollis euismod, ante lectus pulvinar turpis, vel tincidunt augue nulla at purus. Aenean in risus vel massa interdum efficitur. Mauris in sem mauris. Morbi non vehicula leo, ac ultricies diam. Suspendisse pulvinar posuere elit non auctor. Mauris gravida, quam sed feugiat suscipit, justo turpis semper lacus, vitae condimentum tellus arcu eget turpis. Nulla blandit nisi vel risus consequat placerat. Suspendisse accumsan vitae dui vel suscipit. Maecenas porta odio felis, eu euismod enim volutpat sit amet. Nullam et eros mauris. Nullam at tempus nulla, vitae tristique magna. Aliquam sagittis, est a laoreet aliquet, est dolor sodales sem, quis consectetur sapien massa eu mauris. Pellentesque blandit maximus eros, eget luctus nisi sollicitudin ut. Duis risus eros, sodales lobortis finibus id, iaculis ut turpis.

                    <p>Phasellus sollicitudin porta sollicitudin. Suspendisse lobortis, magna ac imperdiet venenatis, massa elit pretium ligula, ut tempus lectus ligula eu tortor. In hendrerit lectus at porta tincidunt. Nulla interdum imperdiet turpis, vitae laoreet magna porta vitae. Pellentesque leo urna, feugiat non ante a, auctor porta ligula. Mauris fringilla nisi id lacinia molestie. Praesent aliquet leo ut sem varius consequat. Nunc hendrerit at purus sit amet varius. Quisque convallis purus nec hendrerit ullamcorper. Aenean at nisi et augue molestie egestas. Sed in lectus cursus turpis rutrum malesuada. Vivamus iaculis lobortis aliquet. Nam id sapien mi. Quisque bibendum velit at fringilla venenatis. Maecenas sagittis lacinia neque, in vulputate tortor accumsan ut. Maecenas neque metus, ultricies ut lobortis vel, suscipit non ante. Quisque luctus, ex nec elementum tristique, arcu elit mollis mi, nec tincidunt nulla sem in lacus. Nullam dapibus diam sed lorem viverra euismod. Integer eu urna egestas, suscipit justo id, iaculis elit. Sed quis elit urna. Nam nec massa eget ligula pharetra dignissim. Suspendisse magna mi, faucibus vitae condimentum in, efficitur nec mi. Suspendisse sed libero auctor sem commodo tincidunt id eget urna. Donec lobortis velit quis dui suscipit gravida. Donec a lacus ultrices, feugiat tellus ac, vestibulum sapien. Vestibulum efficitur tortor ac ultrices lacinia. Vestibulum sollicitudin quis turpis ac ultrices. Quisque id justo placerat, iaculis sem nec, pellentesque massa. Aenean vel libero dapibus tellus dictum vehicula a id nisi. Nullam consectetur quam eu nulla posuere, in pretium ante faucibus. Fusce vitae aliquet orci, a ornare purus. Etiam sit amet lectus mi. Aliquam porttitor dictum bibendum. In volutpat at tellus ac ultrices. Phasellus sed diam orci. Cras venenatis, tortor non pulvinar ullamcorper, quam risus tempor risus, non scelerisque augue sapien consequat velit. Pellentesque efficitur faucibus mi et blandit.</p>

                    <img src="img/concert2.jpg" alt="" style="width: 100%; border-radius: 20px; margin-top: 30px;" class="img_cien" /> 

                    <p id="nag2">Ut ultrices nisi et pretium efficitur. Curabitur ac arcu a augue dignissim interdum ut a orci. Donec ornare, mauris id aliquet ullamcorper, metus est placerat nulla, nec vulputate nisi sem eget lorem. Vestibulum id metus tortor. Sed vestibulum faucibus pretium. Donec accumsan ornare felis eget lobortis. Aenean ornare mi non nisl consectetur hendrerit. Nam consectetur at ipsum in convallis. Quisque accumsan ipsum vel enim facilisis, id rhoncus nisl iaculis. In ac sollicitudin turpis, vel pharetra mauris. Sed euismod auctor odio, pharetra convallis quam sagittis eu. Vivamus vel convallis felis. Curabitur a neque leo. Vestibulum in libero nec nisl mollis facilisis in et sapien. Integer tincidunt augue at orci faucibus venenatis. Maecenas ut enim enim. Fusce a nisl quis turpis consequat faucibus. Vivamus neque leo, pharetra rhoncus feugiat nec, volutpat sed massa. Aenean dignissim elit id suscipit ullamcorper. Aliquam ullamcorper feugiat libero non iaculis. Quisque sodales et elit a faucibus. Pellentesque sit amet nibh tempus, luctus metus et, imperdiet odio. Suspendisse potenti. Morbi non fermentum mauris, non porta nisi. Quisque dignissim, felis nec placerat rutrum, velit ipsum tempus quam, id feugiat quam justo id lacus. Ut ac semper risus, in lobortis mauris. Morbi feugiat libero vel elit rhoncus molestie. Nunc ut tortor dignissim, sollicitudin nisl id, pellentesque diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam et libero eget lorem lobortis congue non eget metus. Vestibulum et urna vitae risus egestas congue id placerat nibh. Maecenas nec justo magna. Donec volutpat orci tellus, ac consequat arcu gravida in. Fusce consequat posuere nibh, in feugiat sapien pulvinar in. Nunc venenatis ac augue et imperdiet. Pellentesque finibus ultricies quam. Phasellus elementum nulla id mauris tempus posuere.</p>
                </section>

                <hr>

                <section>
                    <div class="podnaglowek" id="przyszle">Przyszłe koncerty</div>

                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum diam ante, id lacinia est aliquet tincidunt. Fusce egestas, enim in consectetur cursus, tellus dui finibus mi, id tincidunt odio justo vitae sapien. Vestibulum ac eleifend mi, auctor efficitur dui. Duis semper, justo id ultricies commodo, lorem massa malesuada risus, id bibendum erat neque a quam. Nullam sed sem facilisis, consequat ipsum sit amet, tempor risus. Phasellus laoreet quis eros non accumsan. Suspendisse molestie viverra orci sit amet venenatis. Aliquam mattis metus nec fermentum tempor. Vestibulum interdum posuere urna, non condimentum lorem blandit sed. Fusce fermentum pulvinar justo eu ultricies. Integer hendrerit metus diam, volutpat aliquam purus hendrerit in. Morbi non lacus vel lorem ornare tincidunt. Nullam consequat feugiat orci, eu aliquam massa condimentum eget. Phasellus vitae molestie sapien. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur id urna fermentum, finibus massa sed, suscipit purus. Proin eu metus porta libero sollicitudin cursus. In at fermentum dolor. Donec eget est eget orci rutrum porta vitae eget nibh. Nunc vitae viverra justo. Etiam at urna orci. Aenean sagittis tortor lectus, rutrum blandit eros consectetur id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus a consequat eros. Quisque a sapien vitae leo porttitor tempus a ut ex. Vivamus sed luctus sapien.</p>

                    <p>Morbi pharetra velit tincidunt nunc feugiat commodo. Curabitur laoreet ultrices felis, nec pulvinar massa sagittis eu. Maecenas vel quam ut leo lobortis gravida. Praesent a lobortis neque, posuere consectetur erat. Proin venenatis ac magna finibus imperdiet. Proin vitae pellentesque eros. Morbi in fringilla ex. Cras ultrices ante nec dictum placerat. Mauris maximus dui non nunc porta, quis aliquet mi cursus. Morbi aliquam purus at sapien dictum laoreet. Vestibulum vel sem laoreet massa lobortis pretium a non risus. Cras vitae purus in sem venenatis finibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut rutrum neque tellus, non viverra neque malesuada quis. Duis fermentum nibh et sollicitudin hendrerit. Phasellus sed eros facilisis mi porta tempor. Etiam porttitor ipsum in leo imperdiet, a varius leo interdum. Donec faucibus, lectus eget sollicitudin lacinia, nisi justo ullamcorper erat, a lobortis tortor libero nec magna. Sed dignissim velit at magna semper, in bibendum eros feugiat. Cras quam eros, consequat pellentesque accumsan non, pretium in arcu. Mauris congue id nibh non varius. Donec vitae libero ornare, laoreet erat at, pretium est. Pellentesque congue hendrerit magna at vulputate. Nulla congue fringilla velit. Suspendisse id suscipit erat.</p>

                    <p id="nag3">Curabitur quis risus vel odio mollis molestie. Morbi ut consectetur lorem. Donec euismod turpis volutpat, maximus turpis ac, pellentesque ex. Proin turpis libero, venenatis id interdum ut, semper ut lectus. Aliquam posuere suscipit orci non lobortis. Duis nulla eros, scelerisque sed feugiat non, dictum eu purus. Fusce magna odio, sollicitudin sit amet faucibus non, accumsan et lectus. Donec a justo at orci semper tristique. Quisque lectus orci, porttitor sit amet commodo ut, vehicula vel leo. Suspendisse mollis feugiat est vitae suscipit. Maecenas fringilla, tortor sit amet convallis vehicula, augue erat porttitor massa, id tempor dolor dolor eu ex. Donec dictum, neque eu congue rutrum, ligula sem accumsan nunc, vitae maximus nisl nibh elementum nisl. Etiam volutpat ipsum eget augue maximus, sit amet convallis leo suscipit. Sed quis ipsum nisl. Fusce consectetur leo vel pharetra ultricies. Nulla venenatis eleifend metus ac porta. Curabitur nec nibh euismod, tincidunt quam in, pellentesque ex. Praesent rhoncus tortor vel mauris porttitor, vel commodo magna tempor. Proin sem tortor, ultricies quis est ac, finibus volutpat nulla.</p>
                </section>

                <hr>

                <section>
                    <div class="podnaglowek" id="mapa_trasy">Mapa trasy</div>
                    <img src="img/concert3.jpg" alt="" style="width: 100%; border-radius: 20px; margin-top: 30px;" class="img_cien" /> 

                    <p>Morbi pharetra velit tincidunt nunc feugiat commodo. Curabitur laoreet ultrices felis, nec pulvinar massa sagittis eu. Maecenas vel quam ut leo lobortis gravida. Praesent a lobortis neque, posuere consectetur erat. Proin venenatis ac magna finibus imperdiet. Proin vitae pellentesque eros. Morbi in fringilla ex. Cras ultrices ante nec dictum placerat. Mauris maximus dui non nunc porta, quis aliquet mi cursus. Morbi aliquam purus at sapien dictum laoreet. Vestibulum vel sem laoreet massa lobortis pretium a non risus. Cras vitae purus in sem venenatis finibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut rutrum neque tellus, non viverra neque malesuada quis. Duis fermentum nibh et sollicitudin hendrerit. Phasellus sed eros facilisis mi porta tempor. Etiam porttitor ipsum in leo imperdiet, a varius leo interdum. Donec faucibus, lectus eget sollicitudin lacinia, nisi justo ullamcorper erat, a lobortis tortor libero nec magna. Sed dignissim velit at magna semper, in bibendum eros feugiat. Cras quam eros, consequat pellentesque accumsan non, pretium in arcu. Mauris congue id nibh non varius. Donec vitae libero ornare, laoreet erat at, pretium est. Pellentesque congue hendrerit magna at vulputate. Nulla congue fringilla velit. Suspendisse id suscipit erat. Curabitur quis risus vel odio mollis molestie. Morbi ut consectetur lorem. Donec euismod turpis volutpat, maximus turpis ac, pellentesque ex. Proin turpis libero, venenatis id interdum ut, semper ut lectus. Aliquam posuere suscipit orci non lobortis. Duis nulla eros, scelerisque sed feugiat non, dictum eu purus</p>
                </section>

            </div>
        </article>
    </main>



<?php
    require_once "end.php";
?>

